stages:
   - build
   - deploy

# build stage
build_app:
   image: node:alpine
   stage: build
   only:
      - master
   script: 
      - npm install 
      - npm run build  
   cache:
     paths:
       - node_modules/ 
   artifacts:
      paths:
         # build folder
         - dist/
      expire_in: 1 hour

# production stage
production:
   image: python:alpine
   stage: deploy
   only:
      - master
   script:
      - pip install awscli
      - aws s3 sync ./dist s3://abay-textile